# Generated by Django 3.2.7 on 2021-11-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='images/Photography/Category')),
            ],
            options={
                'verbose_name_plural': 'Photo Categories',
            },
        ),
        migrations.CreateModel(
            name='SignatureRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='images/Cookbook')),
            ],
            options={
                'verbose_name_plural': 'Signature Recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('preparation', models.TextField(blank=True, null=True)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.signaturerecipe')),
            ],
            options={
                'verbose_name_plural': 'Recipe Details',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/Photography/All Photos/')),
                ('title', models.CharField(max_length=200)),
                ('orientation', models.CharField(choices=[('Horizontal', 'Horizontal'), ('Vertical', 'Vertical')], default='Horizontal', max_length=200)),
                ('placement', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=200)),
                ('photo_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.photocategory')),
            ],
        ),
    ]
