# Generated by Django 3.2.7 on 2021-11-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetail',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipedetail',
            name='preparation',
            field=models.TextField(default=''),
        ),
    ]
