# Generated by Django 3.2.7 on 2021-11-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211123_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedetail',
            name='cooking_method',
            field=models.TextField(default=''),
        ),
    ]
