# Generated by Django 3.2.7 on 2021-12-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recipedetail_cooking_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('top_picture', models.ImageField(upload_to='images/Projects/Project Detail/')),
                ('description', models.TextField(default='')),
                ('tools_used', models.TextField(default='')),
                ('github_link', models.TextField(default='')),
                ('middle_picture', models.ImageField(upload_to='images/Projects/Project Detail/')),
                ('context', models.TextField(default='')),
                ('goals', models.TextField(default='')),
                ('potential_improvements', models.TextField(default='')),
                ('bottom_picture', models.ImageField(upload_to='images/Projects/Project Detail/')),
            ],
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='profile_picture',
            field=models.ImageField(upload_to='images/Photography/Category/'),
        ),
        migrations.AlterField(
            model_name='signaturerecipe',
            name='profile_picture',
            field=models.ImageField(upload_to='images/Cookbook/'),
        ),
    ]
