# Generated by Django 3.2.7 on 2021-12-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211202_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_picture', models.ImageField(upload_to='images/Projects/Project Summary/')),
                ('summary', models.TextField(default='')),
                ('github_link', models.CharField(max_length=200)),
                ('additional_links', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Project Summaries',
            },
        ),
        migrations.AlterModelOptions(
            name='projectdetail',
            options={'verbose_name_plural': 'Project Details'},
        ),
    ]
