# Generated by Django 3.2.7 on 2021-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211202_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsummary',
            name='additional_links',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
