# Generated by Django 3.2.7 on 2021-12-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_projectsummary_additional_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.projectsummary'),
        ),
    ]
