# Generated by Django 3.2.7 on 2021-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_projectdetail_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='github_link',
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
