# Generated by Django 3.2.7 on 2021-12-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_projectdetail_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='images/Library/Categories/')),
            ],
            options={
                'verbose_name_plural': 'Book Categories',
            },
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='profile_picture',
            field=models.ImageField(upload_to='images/Photography/Categories/'),
        ),
    ]
