# Generated by Django 3.2.7 on 2021-12-05 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211204_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='images/Library/All Books/')),
                ('author', models.CharField(max_length=200)),
                ('book_review', models.TextField(default='')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookcategory')),
            ],
        ),
    ]
