# Generated by Django 3.2.7 on 2021-12-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='placement',
        ),
    ]
