# Generated by Django 3.2.7 on 2021-12-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211206_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_logo', models.ImageField(upload_to='images/Experience/')),
                ('type', models.CharField(choices=[('Work Experience', 'Work Experience'), ('Volunteer Experience', 'Volunteer Experience')], max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='Start Date (mm/dd/yyyy)')),
                ('end_date', models.DateField(verbose_name='End Date (mm/dd/yyyy):')),
                ('tasks', models.TextField(default='')),
                ('results', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='goals',
            field=models.TextField(default='', verbose_name='Goals (Format: 1), 2)):'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='potential_improvements',
            field=models.TextField(default='', verbose_name='Potential Improvements (Format: 1), 2))'),
        ),
        migrations.AlterField(
            model_name='projectsummary',
            name='additional_links',
            field=models.TextField(blank=True, default='', null=True, verbose_name="Additional Links (Format: 'Alias': 'url'):"),
        ),
    ]
