# Generated by Django 3.2.7 on 2021-12-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211206_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='organization_logo',
        ),
    ]
