# Generated by Django 3.2.7 on 2021-12-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_experience_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='organization_logo',
            field=models.ImageField(upload_to='images/Experience/'),
        ),
    ]
