# Generated by Django 3.2.7 on 2021-12-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_experience_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='results',
            field=models.TextField(default='', verbose_name='Results (Format: 1), 2)):'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tasks',
            field=models.TextField(default='', verbose_name='Tasks (Format: 1), 2)):'),
        ),
    ]
