# Generated by Django 3.2.7 on 2022-01-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_skilltype_tool'),
    ]

    operations = [
        migrations.RenameModel('BookCategory', 'BookGenre'),
        migrations.RenameField('Book', 'book_category', 'book_genre')
    ]
